# Generated by Django 5.0.7 on 2024-08-13 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_default=datetime.datetime(2024, 8, 13, 10, 26, 24, 822337, tzinfo=datetime.timezone.utc), verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, db_default=datetime.datetime(2024, 8, 13, 10, 26, 24, 822364, tzinfo=datetime.timezone.utc), verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], db_default='user', max_length=20),
        ),
    ]
